#公共配置
server:
    port: 8080
    tomcat:
      uri-encoding: UTF-8
spring:
  #视图配置
  mvc:
    static-path-pattern: /static/**
  #网络请求配置
  http:
      encoding:
        force: true
        charset: UTF-8
        enabled: true
      multipart:
        location: /opt/data
  #模板引擎配置
  freemarker:
      template-loader-path: classpath:/templates/
      prefer-file-system-access: false
      settings:
        template_update_delay: 0
        classic_compatible: true
        number_format: 0.######
        template_exception_handler: ignore
      request-context-attribute: rc
      charset: UTF-8
  #连接池配置
  datasource:
    url: jdbc:mysql://124.221.143.166:3309/hb?useUnicode=true&characterEncoding=utf8&useSSL=false&tinyInt1isBit=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      validationQuery: SELECT 1
      initialSize: 10
      minIdle: 10
      maxActive: 200
      minEvictableIdleTimeMillis: 180000
      testOnBorrow: false
      testWhileIdle: true
      removeAbandoned: true
      # 活动线程最大存活时间，超过直接丢弃（单位分钟）
      removeAbandonedTimeout: 180
      logAbandoned: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  #实体扫描，多个package用逗号或者分号隔离
  typeAliasesPackage: com.luo.manage.entity
  # SQL打印
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
#    call-setters-on-nulls: true
  # 全局id生成策略：注解 > 全局 > 默认
  global-config:
      db-config:
          id-type: none
          refresh-mapper: true
      banner: false


file:
  uploadFolder: D:/resources/upload/
  staticAccessPath:  /upload/**

company: 深圳图南环保技术有限公司
companyAddres: 深圳市南山区南头街道田厦社区学府路桃苑公寓22号-1桃苑公寓338
email: 865872583@qq.com
phone: 13553992423
icp1: 粤ICP备2022054595号
icp2: 44030502009034
