#公共配置
server:
    port: 9004
    tomcat:
      uri-encoding: UTF-8
spring:
  #视图配置
  mvc:
    static-path-pattern: /static/**
  #网络请求配置
  http:
      encoding:
        force: true
        charset: UTF-8
        enabled: true
      multipart:
          max-file-size: 100MB
          max-request-size: 100MB
          enabled: true
  #模板引擎配置
  freemarker:
      template-loader-path: classpath:/templates/
      prefer-file-system-access: false
      settings:
        template_update_delay: 0
        classic_compatible: true
        number_format: 0.######
        template_exception_handler: ignore
      request-context-attribute: rc
      charset: UTF-8
  #连接池配置
  datasource:
    url: jdbc:mysql://192.168.0.109:3308/hb?useUnicode=true&characterEncoding=utf8&useSSL=false&tinyInt1isBit=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      validationQuery: SELECT 1
      initialSize: 10
      minIdle: 10
      maxActive: 200
      minEvictableIdleTimeMillis: 180000
      testOnBorrow: false
      testWhileIdle: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100
      connection-init-sqls: set names utf8mb4
  redis:
      host: 192.168.0.109
      port: 6379
      timeout: 6000  # 连接超时时长（毫秒）
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  #缓存配置
  cache:
      type: redis
      cache-names: luo
  devtools:
    restart:
      enabled: false

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  #实体扫描，多个package用逗号或者分号隔离
  typeAliasesPackage: com.luo.manage.entity
  # SQL打印
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
   # call-setters-on-nulls: true
  # 全局id生成策略：注解 > 全局 > 默认
  global-config:
      db-config:
          id-type: none
          refresh-mapper: true
      banner: false

file:
  uploadFolder: E:/upload/
  staticAccessPath:  /upload/**

logging:
  config: classpath:log/logback.xml
  path: E:\log\luo
  level: debug

